APPLICATION_FONT_RESOURCE = ":/fonts/roboto_regular"
APPLICATION_FONT_FAMILY_NAME = "Roboto"
APPLICATION_FONT_SIZE = 14

APPLICATION_NAME = "Person Location Detector"

CAMERA_FRAMES_TO_PROCESS_MAX_NUMBER = 1